### PR TITLE
WIP: ICU package update

### PR DESCRIPTION
**Pull request by anmode**
When I try to setup project faced this issue!

```npm ERR! code 1
npm ERR! path /Users/anmolagrawal/Desktop/Opensource/wikidocumentaries/wikidocumentaries-api/node_modules/full-icu
npm ERR! command failed
npm ERR! command sh -c -- node postinstall.js
npm ERR! Note: Your node was not compiled with the ‘small-icu’ case, so the ICU data is not customizable through this script. Exitting.
npm ERR! npm install icu4c-data@72l (Node 18.13.0 and small-icu 72.1) -> icudt72l.dat
npm ERR! full-icu$ /usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js install icu4c-data@72l
npm ERR! npm ERR! code ETARGET
npm ERR! npm ERR! notarget No matching version found for icu4c-data@72l.
npm ERR! npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! npm ERR! notarget a package version that doesn't exist.
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /Users/anmolagrawal/.npm/_logs/2023-02-16T04_02_59_179Z-debug-0.log
npm ERR! /Users/anmolagrawal/Desktop/Opensource/wikidocumentaries/wikidocumentaries-api/node_modules/full-icu/install-spawn.js:41
npm ERR!                throw(Error(cmdPath + ' ' + args.join(' ') + ' --> status ' + spawned.status));
npm ERR!                ^
npm ERR! 
npm ERR! Error: /usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js install icu4c-data@72l --> status 1
npm ERR!     at npmInstallNpm (/Users/anmolagrawal/Desktop/Opensource/wikidocumentaries/wikidocumentaries-api/node_modules/full-icu/install-spawn.js:41:9)
npm ERR!     at Object.<anonymous> (/Users/anmolagrawal/Desktop/Opensource/wikidocumentaries/wikidocumentaries-api/node_modules/full-icu/postinstall.js:68:2)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1218:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1081:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:922:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
npm ERR!     at node:internal/main/run_main_module:23:47
npm ERR! 
npm ERR! Node.js v18.13.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/anmolagrawal/.npm/_logs/2023-02-16T04_02_51_113Z-debug-0.log```



I think Every new contributor will surely face this issue so created the PR and also updated `package.json`

### CODE REVIEW

**Comment by tuukka** [comment]
Thank you! Could you rebase this pull request on top of the latest `master` branch (or merge from the `master` branch)? I had to fix the CI so that the tests could pass here.

**Comment by anmode** [comment]
Sure! done. Thank you!!

**Comment by tuukka** [comment]
The upgrades to NodeJS 16, package-lock.json format v2 and full-icu 1.5.0 needed to be done step by step, see #28

**Comment by anmode** [comment]
> The upgrades to NodeJS 16, package-lock.json format v2 and full-icu 1.5.0 needed to be done step by step, see #28 

Ohh okay got that!! Thank you.

**Pull request closed without merging**
